
---
- name: Configure master node
  hosts: master
  tasks:
    - name: Install PostgreSQL client
      ansible.builtin.package:
        name: postgresql-client
        state: present

    - name: Connect to Cloud SQL PostgreSQL
      ansible.builtin.shell: >
        PGPASSWORD={{ db_password }} psql -h /cloudsql/{{ cloud_sql_instance_connection_name }}
        -U {{ db_user }} -d {{ db_name }} -c "SELECT 1"
      register: psql_output

    - name: Ensure connection to PostgreSQL is successful
      ansible.builtin.debug:
        msg: "PostgreSQL connection successful: {{ psql_output.stdout }}"
      failed_when: "'1' not in psql_output.stdout"

- name: Configure worker nodes
  hosts: workers
  tasks:
    - name: Install PostgreSQL client
      ansible.builtin.package:
        name: postgresql-client
        state: present

    - name: Connect to Cloud SQL PostgreSQL
      ansible.builtin.shell: >
        PGPASSWORD={{ db_password }} psql -h /cloudsql/{{ cloud_sql_instance_connection_name }}
        -U {{ db_user }} -d {{ db_name }} -c "SELECT 1"
      register: psql_output

    - name: Ensure connection to PostgreSQL is successful
      ansible.builtin.debug:
        msg: "PostgreSQL connection successful: {{ psql_output.stdout }}"
      failed_when: "'1' not in psql_output.stdout"

